# Generated by Django 6.1.1 on 2026-09-02 20:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('source', models.TextField(help_text='Rego source; must declare `package policies`.')),
            ],
            options={
                'verbose_name_plural': 'policies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PolicySet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PolicySetBinding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='opa_policy_binding', to='contenttypes.contenttype')),
                ('policy_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bindings', to='django_opa_permissions.policyset')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PolicySetMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='django_opa_permissions.policy')),
                ('policy_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='django_opa_permissions.policyset')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.AddField(
            model_name='policyset',
            name='policies',
            field=models.ManyToManyField(blank=True, related_name='policy_sets', through='django_opa_permissions.PolicySetMembership', to='django_opa_permissions.policy'),
        ),
        migrations.AddConstraint(
            model_name='policysetmembership',
            constraint=models.UniqueConstraint(fields=('policy', 'policy_set'), name='unique_policy_per_set'),
        ),
    ]
