# Generated by Django 6.1.1 on 2026-09-02 20:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicySet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('source', models.TextField(help_text='Rego source; must declare `package policies`.')),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('policy_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='django_opa_permissions.policyset')),
            ],
            options={
                'verbose_name_plural': 'policies',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PolicySetBinding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='opa_policy_binding', to='contenttypes.contenttype')),
                ('policy_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bindings', to='django_opa_permissions.policyset')),
            ],
        ),
    ]
